mutation {
  movie_insertMany(
    data: [
      {
        id: "550e8400-e29b-41d4-a716-446655440000"
        title: "Quantum Paradox"
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/fdc-web-quickstart.appspot.com/o/movie%2Fquantum_paradox.jpeg?alt=media&token=4142e2a1-bf43-43b5-b7cf-6616be3fd4e3"
        releaseYear: 2025
        genre: "sci-fi"
        rating: 7.9
        description: "A group of scientists accidentally open a portal to a parallel universe, causing a rift in time. As the team races to close the portal, they encounter alternate versions of themselves, leading to shocking revelations."
        tags: ["thriller", "adventure"]
      }
      {
        id: "550e8400-e29b-41d4-a716-446655440001"
        title: "The Lone Outlaw"
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/fdc-web-quickstart.appspot.com/o/movie%2Flone_outlaw.jpeg?alt=media&token=15525ffc-208f-4b59-b506-ae8348e06e85"
        releaseYear: 2023
        genre: "western"
        rating: 8.2
        description: "In the lawless Wild West, a mysterious gunslinger with a hidden past takes on a corrupt sheriff and his band of outlaws to bring justice to a small town."
        tags: ["action", "drama"]
      }
      {
        id: "550e8400-e29b-41d4-a716-446655440002"
        title: "Celestial Harmony"
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/fdc-web-quickstart.appspot.com/o/movie%2Fcelestial_harmony.jpeg?alt=media&token=3edf1cf9-c2f5-4c75-9819-36ff6a734c9a"
        releaseYear: 2024
        genre: "romance"
        rating: 7.5
        description: "Two astronauts, stationed on a remote space station, fall in love amidst the isolation of deep space. But when a mysterious signal disrupts their communication, they must find a way to reconnect and survive."
        tags: ["romance", "sci-fi"]
      }
      {
        id: "550e8400-e29b-41d4-a716-446655440003"
        title: "Noir Mystique"
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/fdc-web-quickstart.appspot.com/o/movie%2Fnoir_mystique.jpeg?alt=media&token=3299adba-cb98-4302-8b23-aeb679a4f913"
        releaseYear: 2022
        genre: "mystery"
        rating: 8.0
        description: "A private detective gets caught up in a web of lies, deception, and betrayal while investigating the disappearance of a famous actress in 1940s Hollywood."
        tags: ["crime", "thriller"]
      }
      {
        id: "550e8400-e29b-41d4-a716-446655440004"
        title: "The Forgotten Island"
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/fdc-web-quickstart.appspot.com/o/movie%2Fforgotten_island.jpeg?alt=media&token=bc2b16e1-caed-4649-952c-73b6113f205c"
        releaseYear: 2025
        genre: "adventure"
        rating: 7.6
        description: "An explorer leads an expedition to a remote island rumored to be home to mythical creatures. As the team ventures deeper into the island, they uncover secrets that change the course of history."
        tags: ["adventure", "fantasy"]
      }
      {
        id: "550e8400-e29b-41d4-a716-446655440005"
        title: "Digital Nightmare"
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/fdc-web-quickstart.appspot.com/o/movie%2Fdigital_nightmare.jpeg?alt=media&token=335ec842-1ca4-4b09-abd1-e96d9f5c0c2f"
        releaseYear: 2024
        genre: "horror"
        rating: 6.9
        description: "A tech-savvy teenager discovers a cursed app that brings nightmares to life. As the horrors of the digital world cross into reality, she must find a way to break the curse before it's too late."
        tags: ["horror", "thriller"]
      }
      {
        id: "550e8400-e29b-41d4-a716-446655440006"
        title: "Eclipse of Destiny"
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/fdc-web-quickstart.appspot.com/o/movie%2Feclipse_destiny.jpeg?alt=media&token=346649b3-cb5c-4d7e-b0d4-6f02e3df5959"
        releaseYear: 2026
        genre: "fantasy"
        rating: 8.1
        description: "In a kingdom on the brink of war, a prophecy speaks of an eclipse that will grant power to the rightful ruler. As factions vie for control, a young warrior must decide where his true loyalty lies."
        tags: ["fantasy", "adventure"]
      }
      {
        id: "550e8400-e29b-41d4-a716-446655440007"
        title: "Heart of Steel"
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/fdc-web-quickstart.appspot.com/o/movie%2Fheart_steel.jpeg?alt=media&token=17883d71-329b-415a-86f8-dd4d9e941d7f"
        releaseYear: 2023
        genre: "sci-fi"
        rating: 7.7
        description: "A brilliant scientist creates a robot with a human heart. As the robot struggles to understand emotions, it becomes entangled in a plot that could change the fate of humanity."
        tags: ["sci-fi", "drama"]
      }
      {
        id: "550e8400-e29b-41d4-a716-446655440008"
        title: "Rise of the Crimson Empire"
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/fdc-web-quickstart.appspot.com/o/movie%2Frise_crimson_empire.jpeg?alt=media&token=6faa73ad-7504-4146-8f3a-50b90f607f33"
        releaseYear: 2025
        genre: "action"
        rating: 8.4
        description: "A legendary warrior rises to challenge the tyrannical rule of a powerful empire. As rebellion brews, the warrior must unite different factions to lead an uprising."
        tags: ["action", "adventure"]
      }
      {
        id: "550e8400-e29b-41d4-a716-446655440009"
        title: "Silent Waves"
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/fdc-web-quickstart.appspot.com/o/movie%2Fsilent_waves.jpeg?alt=media&token=bd626bf1-ec60-4e57-aa07-87ba14e35bb7"
        releaseYear: 2024
        genre: "drama"
        rating: 8.2
        description: "A talented pianist, who loses his hearing in a tragic accident, must rediscover his passion for music with the help of a young music teacher who believes in him."
        tags: ["drama", "music"]
      }
      {
        id: "550e8400-e29b-41d4-a716-446655440010"
        title: "Echoes of the Past"
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/fdc-web-quickstart.appspot.com/o/movie%2Fecho_of_past.jpeg?alt=media&token=d866aa27-8534-4d72-8988-9da4a1b9e452"
        releaseYear: 2023
        genre: "historical"
        rating: 7.8
        description: "A historian stumbles upon an ancient artifact that reveals hidden truths about an empire long forgotten. As she deciphers the clues, a shadowy organization tries to stop her from unearthing the past."
        tags: ["drama", "mystery"]
      }
      {
        id: "550e8400-e29b-41d4-a716-446655440011"
        title: "Beyond the Horizon"
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/fdc-web-quickstart.appspot.com/o/movie%2Fbeyond_horizon.jpeg?alt=media&token=31493973-0692-4e6e-8b88-afb1aaea17ee"
        releaseYear: 2026
        genre: "sci-fi"
        rating: 8.5
        description: "In the future, Earth's best pilots are sent on a mission to explore a mysterious planet beyond the solar system. What they find changes humanity's understanding of the universe forever."
        tags: ["sci-fi", "adventure"]
      }
      {
        id: "550e8400-e29b-41d4-a716-446655440012"
        title: "Shadows and Lies"
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/fdc-web-quickstart.appspot.com/o/movie%2Fshadows_lies.jpeg?alt=media&token=01afb80d-caee-47f8-a00e-aea8b9e459a2"
        releaseYear: 2022
        genre: "crime"
        rating: 7.9
        description: "A young detective with a dark past investigates a series of mysterious murders in a city plagued by corruption. As she digs deeper, she realizes nothing is as it seems."
        tags: ["crime", "thriller"]
      }
      {
        id: "550e8400-e29b-41d4-a716-446655440013"
        title: "The Last Symphony"
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/fdc-web-quickstart.appspot.com/o/movie%2Flast_symphony.jpeg?alt=media&token=f9bf80cd-3d8e-4e24-8503-7feb11f4e397"
        releaseYear: 2024
        genre: "drama"
        rating: 8.0
        description: "An aging composer struggling with memory loss attempts to complete his final symphony. With the help of a young prodigy, he embarks on an emotional journey through his memories and legacy."
        tags: ["drama", "music"]
      }
      {
        id: "550e8400-e29b-41d4-a716-446655440014"
        title: "Moonlit Crusade"
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/fdc-web-quickstart.appspot.com/o/movie%2Fmoonlit_crusade.jpeg?alt=media&token=b13241f5-d7d0-4370-b651-07847ad99dc2"
        releaseYear: 2025
        genre: "fantasy"
        rating: 8.3
        description: "A knight is chosen by an ancient order to embark on a quest under the light of the full moon. Facing mythical beasts and treacherous landscapes, he seeks a relic that could save his kingdom."
        tags: ["fantasy", "adventure"]
      }
      {
        id: "550e8400-e29b-41d4-a716-446655440015"
        title: "Abyss of the Deep"
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/fdc-web-quickstart.appspot.com/o/movie%2Fabyss_deep.jpeg?alt=media&token=2417321d-2451-4ec0-9ed6-6297042170e6"
        releaseYear: 2023
        genre: "horror"
        rating: 7.2
        description: "When a group of marine biologists descends into the unexplored depths of the ocean, they encounter a terrifying and ancient force. Now, they must survive as the abyss comes alive."
        tags: ["horror", "thriller"]
      }
      {
        id: "550e8400-e29b-41d4-a716-446655440016"
        title: "Phoenix Rising"
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/fdc-web-quickstart.appspot.com/o/movie%2Fpheonix_rising.jpeg?alt=media&token=7298b1fd-833c-471c-a55d-e8fc798b4ab2"
        releaseYear: 2025
        genre: "action"
        rating: 8.6
        description: "A special forces operative, presumed dead, returns to avenge his fallen comrades. With nothing to lose, he faces a powerful enemy in a relentless pursuit for justice."
        tags: ["action", "thriller"]
      }
      {
        id: "550e8400-e29b-41d4-a716-446655440017"
        title: "The Infinite Knot"
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/fdc-web-quickstart.appspot.com/o/movie%2Finfinite_knot.jpeg?alt=media&token=93d54d93-d933-4663-a6fe-26b707ef823e"
        releaseYear: 2026
        genre: "romance"
        rating: 7.4
        description: "Two souls destined to meet across multiple lifetimes struggle to find each other in a chaotic world. With each incarnation, they get closer, but time itself becomes their greatest obstacle."
        tags: ["romance", "fantasy"]
      }
      {
        id: "550e8400-e29b-41d4-a716-446655440018"
        title: "Parallel Justice"
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/fdc-web-quickstart.appspot.com/o/movie%2Fparalel_justice.jpeg?alt=media&token=4544b5e2-7a1d-46ca-a97f-eb6a490d4288"
        releaseYear: 2024
        genre: "crime"
        rating: 8.1
        description: "A lawyer who can see the outcomes of different timelines must choose between justice and personal gain. When a high-stakes case arises, he faces a moral dilemma that could alter his life forever."
        tags: ["crime", "thriller"]
      }
      {
        id: "550e8400-e29b-41d4-a716-446655440019"
        title: "Veil of Illusion"
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/fdc-web-quickstart.appspot.com/o/movie%2Fveil_illusion.jpeg?alt=media&token=7bf09a3c-c531-478a-9d02-5d99fca9393b"
        releaseYear: 2022
        genre: "mystery"
        rating: 7.8
        description: "A magician-turned-detective uses his skills in illusion to solve crimes. When a series of murders leaves the city in fear, he must reveal the truth hidden behind a veil of deceit."
        tags: ["mystery", "crime"]
      }
    ]
  )
  actor_insertMany(
    data: [
      {
        id: "123e4567-e89b-12d3-a456-426614174020"
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/fdc-web-quickstart.appspot.com/o/actor%2Foliver_blackwood.jpeg?alt=media&token=79cdbc29-c2c6-4dc3-b87f-f6dc4f1a8208"
        name: "Oliver Blackwood"
      }
      {
        id: "123e4567-e89b-12d3-a456-426614174021"
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/fdc-web-quickstart.appspot.com/o/actor%2Femma_westfield.jpeg?alt=media&token=2991c3c9-cfa8-4067-8b26-c5239b6894c4"
        name: "Emma Westfield"
      }
      {
        id: "123e4567-e89b-12d3-a456-426614174022"
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/fdc-web-quickstart.appspot.com/o/actor%2Fjack_stone.jpeg?alt=media&token=74a564aa-d840-4bdd-a8a6-c6b17bbde608"
        name: "Jack Stone"
      }
      {
        id: "123e4567-e89b-12d3-a456-426614174023"
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/fdc-web-quickstart.appspot.com/o/actor%2Fclara_woods.jpeg?alt=media&token=b4ff2a15-ef6d-4f20-86c9-07d67015fb29"
        name: "Clara Woods"
      }
      {
        id: "123e4567-e89b-12d3-a456-426614174024"
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/fdc-web-quickstart.appspot.com/o/actor%2Fnoah_frost.jpeg?alt=media&token=0d08179a-7778-405e-9501-feac43b77a99"
        name: "Noah Frost"
      }
      {
        id: "123e4567-e89b-12d3-a456-426614174025"
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/fdc-web-quickstart.appspot.com/o/actor%2Fisabelle_hart.jpeg?alt=media&token=d4fdf896-0f5b-4c32-91a4-7a541a95e77d"
        name: "Isabella Hart"
      }
      {
        id: "123e4567-e89b-12d3-a456-426614174026"
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/fdc-web-quickstart.appspot.com/o/actor%2Fliam_hale.jpeg?alt=media&token=08e8eeee-b8ef-4e7b-8f97-a1e0b59321cc"
        name: "Liam Hale"
      }
      {
        id: "123e4567-e89b-12d3-a456-426614174027"
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/fdc-web-quickstart.appspot.com/o/actor%2Fsophia_knight.jpeg?alt=media&token=7a79ef21-93e0-46f9-934c-6bbef7b5d430"
        name: "Sophia Knight"
      }
      {
        id: "123e4567-e89b-12d3-a456-426614174028"
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/fdc-web-quickstart.appspot.com/o/actor%2Falex_clay.jpeg?alt=media&token=2a798cdb-f44f-48d5-91bc-9d26a758944e"
        name: "Alexander Clay"
      }
      {
        id: "123e4567-e89b-12d3-a456-426614174029"
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/fdc-web-quickstart.appspot.com/o/actor%2Famelia_stone.jpeg?alt=media&token=34f21ba9-9e28-4708-9e55-f123634ab506"
        name: "Amelia Stone"
      }
      {
        id: "123e4567-e89b-12d3-a456-426614174030"
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/fdc-web-quickstart.appspot.com/o/actor%2Fethan_blake.jpeg?alt=media&token=41352170-a5cd-4088-b8fd-1c4ee0d52cad"
        name: "Ethan Blake"
      }
      {
        id: "123e4567-e89b-12d3-a456-426614174031"
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/fdc-web-quickstart.appspot.com/o/actor%2Fmia_gray.jpeg?alt=media&token=1ba1831a-3ada-485a-b5c9-2d018bf1862b"
        name: "Mia Gray"
      }
      {
        id: "123e4567-e89b-12d3-a456-426614174032"
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/fdc-web-quickstart.appspot.com/o/actor%2Flucas_reed.jpeg?alt=media&token=c74f44f3-ae98-4208-8e67-18c2db65a5c1"
        name: "Lucas Reed"
      }
      {
        id: "123e4567-e89b-12d3-a456-426614174033"
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/fdc-web-quickstart.appspot.com/o/actor%2Fevelyn_harper.jpeg?alt=media&token=b138b308-9589-4dfe-8c50-a6d70f06dfb1"
        name: "Evelyn Harper"
      }
      {
        id: "123e4567-e89b-12d3-a456-426614174034"
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/fdc-web-quickstart.appspot.com/o/actor%2Foscar_smith.jpeg?alt=media&token=d493da85-644d-4d45-a09d-ecb5416645e4"
        name: "Oscar Smith"
      }
      {
        id: "123e4567-e89b-12d3-a456-426614174035"
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/fdc-web-quickstart.appspot.com/o/actor%2Fava_winter.jpeg?alt=media&token=757e4b11-0372-401e-8fa0-61797e90312a"
        name: "Ava Winter"
      }
      {
        id: "123e4567-e89b-12d3-a456-426614174036"
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/fdc-web-quickstart.appspot.com/o/actor%2Fleo_hunt.jpeg?alt=media&token=2cb14738-b39b-47b1-87f9-b45f38245179"
        name: "Leo Hunt"
      }
      {
        id: "123e4567-e89b-12d3-a456-426614174037"
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/fdc-web-quickstart.appspot.com/o/actor%2Flucy_walsh.jpeg?alt=media&token=016a216c-f329-4c10-bbe8-b31425f73c69"
        name: "Lucy Walsh"
      }
      {
        id: "123e4567-e89b-12d3-a456-426614174038"
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/fdc-web-quickstart.appspot.com/o/actor%2Fmason_ford.jpeg?alt=media&token=55388be9-fdc8-483f-8352-c29755ed3574"
        name: "Mason Ford"
      }
      {
        id: "123e4567-e89b-12d3-a456-426614174039"
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/fdc-web-quickstart.appspot.com/o/actor%2Flily_moore.jpeg?alt=media&token=19538aa6-1baf-4033-8fd7-d2a62aa79f51"
        name: "Lily Moore"
      }
    ]
  )
  movieMetadata_insertMany(
    data: [
      {
        movieId: "550e8400-e29b-41d4-a716-446655440000"
        director: "Henry Caldwell"
      }
      {
        movieId: "550e8400-e29b-41d4-a716-446655440001"
        director: "Juliana Mason, Clark Avery"
      }
      {
        movieId: "550e8400-e29b-41d4-a716-446655440002"
        director: "Diana Rivers"
      }
      {
        movieId: "550e8400-e29b-41d4-a716-446655440003"
        director: "Liam Thatcher"
      }
      {
        movieId: "550e8400-e29b-41d4-a716-446655440004"
        director: "Evelyn Hart"
      }
      {
        movieId: "550e8400-e29b-41d4-a716-446655440005"
        director: "Grayson Brooks"
      }
      {
        movieId: "550e8400-e29b-41d4-a716-446655440006"
        director: "Isabella Quinn"
      }
      {
        movieId: "550e8400-e29b-41d4-a716-446655440007"
        director: "Vincent Hale"
      }
      {
        movieId: "550e8400-e29b-41d4-a716-446655440008"
        director: "Amelia Sutton"
      }
      {
        movieId: "550e8400-e29b-41d4-a716-446655440009"
        director: "Lucas Stone"
      }
      {
        movieId: "550e8400-e29b-41d4-a716-446655440010"
        director: "Sophia Langford"
      }
      {
        movieId: "550e8400-e29b-41d4-a716-446655440011"
        director: "Noah Bennett"
      }
      {
        movieId: "550e8400-e29b-41d4-a716-446655440012"
        director: "Chloe Armstrong"
      }
      {
        movieId: "550e8400-e29b-41d4-a716-446655440013"
        director: "Sebastian Crane"
      }
      {
        movieId: "550e8400-e29b-41d4-a716-446655440014"
        director: "Isla Fitzgerald"
      }
      {
        movieId: "550e8400-e29b-41d4-a716-446655440015"
        director: "Oliver Hayes"
      }
      {
        movieId: "550e8400-e29b-41d4-a716-446655440016"
        director: "Mila Donovan"
      }
      {
        movieId: "550e8400-e29b-41d4-a716-446655440017"
        director: "Carter Monroe, Elise Turner"
      }
      {
        movieId: "550e8400-e29b-41d4-a716-446655440018"
        director: "Adrian Blake"
      }
      {
        movieId: "550e8400-e29b-41d4-a716-446655440019"
        director: "Hazel Carter"
      }
    ]
  )
movieActor_insertMany(
  data: [
    {
      movieId: "550e8400-e29b-41d4-a716-446655440000"
      actorId: "123e4567-e89b-12d3-a456-426614174020"
      role: "main"
    }
    {
      movieId: "550e8400-e29b-41d4-a716-446655440000"
      actorId: "123e4567-e89b-12d3-a456-426614174021"
      role: "supporting"
    }
    {
      movieId: "550e8400-e29b-41d4-a716-446655440001"
      actorId: "123e4567-e89b-12d3-a456-426614174021"
      role: "main"
    }
    {
      movieId: "550e8400-e29b-41d4-a716-446655440001"
      actorId: "123e4567-e89b-12d3-a456-426614174022"
      role: "supporting"
    }
    {
      movieId: "550e8400-e29b-41d4-a716-446655440002"
      actorId: "123e4567-e89b-12d3-a456-426614174022"
      role: "main"
    }
    {
      movieId: "550e8400-e29b-41d4-a716-446655440002"
      actorId: "123e4567-e89b-12d3-a456-426614174023"
      role: "supporting"
    }
    {
      movieId: "550e8400-e29b-41d4-a716-446655440003"
      actorId: "123e4567-e89b-12d3-a456-426614174023"
      role: "main"
    }
    {
      movieId: "550e8400-e29b-41d4-a716-446655440003"
      actorId: "123e4567-e89b-12d3-a456-426614174024"
      role: "supporting"
    }
    {
      movieId: "550e8400-e29b-41d4-a716-446655440004"
      actorId: "123e4567-e89b-12d3-a456-426614174024"
      role: "main"
    }
    {
      movieId: "550e8400-e29b-41d4-a716-446655440004"
      actorId: "123e4567-e89b-12d3-a456-426614174025"
      role: "supporting"
    }
    {
      movieId: "550e8400-e29b-41d4-a716-446655440005"
      actorId: "123e4567-e89b-12d3-a456-426614174025"
      role: "main"
    }
    {
      movieId: "550e8400-e29b-41d4-a716-446655440005"
      actorId: "123e4567-e89b-12d3-a456-426614174026"
      role: "supporting"
    }
    {
      movieId: "550e8400-e29b-41d4-a716-446655440006"
      actorId: "123e4567-e89b-12d3-a456-426614174026"
      role: "main"
    }
    {
      movieId: "550e8400-e29b-41d4-a716-446655440006"
      actorId: "123e4567-e89b-12d3-a456-426614174027"
      role: "supporting"
    }
    {
      movieId: "550e8400-e29b-41d4-a716-446655440007"
      actorId: "123e4567-e89b-12d3-a456-426614174027"
      role: "main"
    }
    {
      movieId: "550e8400-e29b-41d4-a716-446655440007"
      actorId: "123e4567-e89b-12d3-a456-426614174028"
      role: "supporting"
    }
    {
      movieId: "550e8400-e29b-41d4-a716-446655440008"
      actorId: "123e4567-e89b-12d3-a456-426614174028"
      role: "main"
    }
    {
      movieId: "550e8400-e29b-41d4-a716-446655440008"
      actorId: "123e4567-e89b-12d3-a456-426614174029"
      role: "supporting"
    }
    {
      movieId: "550e8400-e29b-41d4-a716-446655440009"
      actorId: "123e4567-e89b-12d3-a456-426614174029"
      role: "main"
    }
    {
      movieId: "550e8400-e29b-41d4-a716-446655440009"
      actorId: "123e4567-e89b-12d3-a456-426614174030"
      role: "supporting"
    }
    {
      movieId: "550e8400-e29b-41d4-a716-446655440010"
      actorId: "123e4567-e89b-12d3-a456-426614174030"
      role: "main"
    }
    {
      movieId: "550e8400-e29b-41d4-a716-446655440010"
      actorId: "123e4567-e89b-12d3-a456-426614174031"
      role: "supporting"
    }
    {
      movieId: "550e8400-e29b-41d4-a716-446655440011"
      actorId: "123e4567-e89b-12d3-a456-426614174031"
      role: "main"
    }
    {
      movieId: "550e8400-e29b-41d4-a716-446655440011"
      actorId: "123e4567-e89b-12d3-a456-426614174032"
      role: "supporting"
    }
    {
      movieId: "550e8400-e29b-41d4-a716-446655440012"
      actorId: "123e4567-e89b-12d3-a456-426614174032"
      role: "main"
    }
    {
      movieId: "550e8400-e29b-41d4-a716-446655440012"
      actorId: "123e4567-e89b-12d3-a456-426614174033"
      role: "supporting"
    }
    {
      movieId: "550e8400-e29b-41d4-a716-446655440013"
      actorId: "123e4567-e89b-12d3-a456-426614174033"
      role: "main"
    }
    {
      movieId: "550e8400-e29b-41d4-a716-446655440013"
      actorId: "123e4567-e89b-12d3-a456-426614174034"
      role: "supporting"
    }
    {
      movieId: "550e8400-e29b-41d4-a716-446655440014"
      actorId: "123e4567-e89b-12d3-a456-426614174034"
      role: "main"
    }
    {
      movieId: "550e8400-e29b-41d4-a716-446655440014"
      actorId: "123e4567-e89b-12d3-a456-426614174035"
      role: "supporting"
    }
    {
      movieId: "550e8400-e29b-41d4-a716-446655440015"
      actorId: "123e4567-e89b-12d3-a456-426614174035"
      role: "main"
    }
    {
      movieId: "550e8400-e29b-41d4-a716-446655440015"
      actorId: "123e4567-e89b-12d3-a456-426614174036"
      role: "supporting"
    }
    {
      movieId: "550e8400-e29b-41d4-a716-446655440016"
      actorId: "123e4567-e89b-12d3-a456-426614174036"
      role: "main"
    }
    {
      movieId: "550e8400-e29b-41d4-a716-446655440016"
      actorId: "123e4567-e89b-12d3-a456-426614174037"
      role: "supporting"
    }
    {
      movieId: "550e8400-e29b-41d4-a716-446655440017"
      actorId: "123e4567-e89b-12d3-a456-426614174037"
      role: "main"
    }
    {
      movieId: "550e8400-e29b-41d4-a716-446655440017"
      actorId: "123e4567-e89b-12d3-a456-426614174038"
      role: "supporting"
    }
    {
      movieId: "550e8400-e29b-41d4-a716-446655440018"
      actorId: "123e4567-e89b-12d3-a456-426614174038"
      role: "main"
    }
    {
      movieId: "550e8400-e29b-41d4-a716-446655440018"
      actorId: "123e4567-e89b-12d3-a456-426614174039"
      role: "supporting"
    }
    {
      movieId: "550e8400-e29b-41d4-a716-446655440019"
      actorId: "123e4567-e89b-12d3-a456-426614174039"
      role: "main"
    }
    {
      movieId: "550e8400-e29b-41d4-a716-446655440019"
      actorId: "123e4567-e89b-12d3-a456-426614174020"
      role: "supporting"
    }
  ]
)
  user_insertMany(
    data: [
      { id: "SnLgOC3lN4hcIl69s53cW0Q8R1T2", username: "sherlock_h" }
      { id: "fep4fXpGWsaRpuphq9CIrBIXQ0S2", username: "hercule_p" }
      { id: "TBedjwCX0Jf955Uuoxk6k74sY0l1", username: "jane_d" }
    ]
  )

  review_insertMany(
    data: [
      {
        id: "345e4567-e89b-12d3-a456-426614174000"
        userId: "SnLgOC3lN4hcIl69s53cW0Q8R1T2"
        movieId: "550e8400-e29b-41d4-a716-446655440000"
        rating: 5
        reviewText: "An incredible movie with a mind-blowing plot!"
        reviewDate_date: { today: true }
      }
      {
        id: "345e4567-e89b-12d3-a456-426614174001"
        userId: "fep4fXpGWsaRpuphq9CIrBIXQ0S2"
        movieId: "550e8400-e29b-41d4-a716-446655440001"
        rating: 5
        reviewText: "A revolutionary film that changed cinema forever."
        reviewDate_date: { today: true }
      }
      {
        id: "345e4567-e89b-12d3-a456-426614174002"
        userId: "TBedjwCX0Jf955Uuoxk6k74sY0l1"
        movieId: "550e8400-e29b-41d4-a716-446655440002"
        rating: 5
        reviewText: "A visually stunning and emotionally impactful movie."
        reviewDate_date: { today: true }
      }
      {
        id: "345e4567-e89b-12d3-a456-426614174003"
        userId: "SnLgOC3lN4hcIl69s53cW0Q8R1T2"
        movieId: "550e8400-e29b-41d4-a716-446655440003"
        rating: 4
        reviewText: "A fantastic superhero film with great performances."
        reviewDate_date: { today: true }
      }
      {
        id: "345e4567-e89b-12d3-a456-426614174004"
        userId: "fep4fXpGWsaRpuphq9CIrBIXQ0S2"
        movieId: "550e8400-e29b-41d4-a716-446655440004"
        rating: 5
        reviewText: "An amazing film that keeps you on the edge of your seat."
        reviewDate_date: { today: true }
      }
      {
        id: "345e4567-e89b-12d3-a456-426614174005"
        userId: "TBedjwCX0Jf955Uuoxk6k74sY0l1"
        movieId: "550e8400-e29b-41d4-a716-446655440005"
        rating: 5
        reviewText: "An absolute classic with unforgettable dialogue."
        reviewDate_date: { today: true }
      }
    ]
  )

  favorite_movie_insertMany(
    data: [
      {
        userId: "SnLgOC3lN4hcIl69s53cW0Q8R1T2"
        movieId: "550e8400-e29b-41d4-a716-446655440000"
      }
      {
        userId: "fep4fXpGWsaRpuphq9CIrBIXQ0S2"
        movieId: "550e8400-e29b-41d4-a716-446655440001"
      }
      {
        userId: "TBedjwCX0Jf955Uuoxk6k74sY0l1"
        movieId: "550e8400-e29b-41d4-a716-446655440002"
      }
      {
        userId: "SnLgOC3lN4hcIl69s53cW0Q8R1T2"
        movieId: "550e8400-e29b-41d4-a716-446655440003"
      }
      {
        userId: "fep4fXpGWsaRpuphq9CIrBIXQ0S2"
        movieId: "550e8400-e29b-41d4-a716-446655440004"
      }
      {
        userId: "TBedjwCX0Jf955Uuoxk6k74sY0l1"
        movieId: "550e8400-e29b-41d4-a716-446655440005"
      }
    ]
  )
}
