-include proguard-rules.pro
-keepattributes SourceFile,LineNumberTable
-dontwarn org.xmlpull.v1.**
-dontnote org.xmlpull.v1.**
-keep class org.xmlpull.** { *; }
-keepclassmembers class org.xmlpull.** { *; }
-keep class com.google.firebase.auth.** {*;}